---
title: "Question 2 Graph"
output: html_document
date: "2023-04-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(shiny)
library(plotly)
```

```{r pressure, echo=FALSE}
# Add weekday/weekend label to dataframes
amsterdam_weekdays <- read.csv("amsterdam_weekdays.csv")
amsterdam_weekdays <- amsterdam_weekdays %>%
  add_column(dayofweek = "weekday")
amsterdam_weekends <- read.csv("amsterdam_weekends.csv")
amsterdam_weekends <- amsterdam_weekends %>%
  add_column(dayofweek = "weekend")

athens_weekdays <- read.csv("athens_weekdays.csv")
athens_weekdays <- athens_weekdays %>%
  add_column(dayofweek = "weekday")
athens_weekends <- read.csv("athens_weekends.csv")
athens_weekends <- athens_weekends %>%
  add_column(dayofweek = "weekend")

barcelona_weekdays <- read.csv("barcelona_weekdays.csv")
barcelona_weekdays <- barcelona_weekdays %>%
  add_column(dayofweek = "weekday")
barcelona_weekends <- read.csv("barcelona_weekends.csv")
barcelona_weekends <- barcelona_weekends %>%
  add_column(dayofweek = "weekend")

berlin_weekdays <- read.csv("berlin_weekdays.csv")
berlin_weekdays <- berlin_weekdays %>%
  add_column(dayofweek = "weekday")
berlin_weekends <- read.csv("berlin_weekends.csv")
berlin_weekends <- berlin_weekends %>%
  add_column(dayofweek = "weekend")

budapest_weekdays <- read.csv("budapest_weekdays.csv")
budapest_weekdays <- budapest_weekdays %>%
  add_column(dayofweek = "weekday")
budapest_weekends <- read.csv("budapest_weekends.csv")
budapest_weekends <- budapest_weekends %>%
  add_column(dayofweek = "weekend")

lisbon_weekdays <- read.csv("lisbon_weekdays.csv")
lisbon_weekdays <- lisbon_weekdays %>%
  add_column(dayofweek = "weekday")
lisbon_weekends <- read.csv("lisbon_weekends.csv")
lisbon_weekends <- lisbon_weekends %>%
  add_column(dayofweek = "weekend")

london_weekdays <- read.csv("london_weekdays.csv")
london_weekdays <- london_weekdays %>%
  add_column(dayofweek = "weekday")
london_weekends <- read.csv("london_weekends.csv")
london_weekends <- london_weekends %>%
  add_column(dayofweek = "weekend")

paris_weekdays <- read.csv("paris_weekdays.csv")
paris_weekdays <- paris_weekdays %>%
  add_column(dayofweek = "weekday")
paris_weekends <- read.csv("paris_weekends.csv")
paris_weekends <-  paris_weekends %>%
  add_column(dayofweek = "weekend")

rome_weekdays <- read.csv("rome_weekdays.csv")
rome_weekdays <- rome_weekdays %>%
  add_column(dayofweek = "weekday")
rome_weekends <- read.csv("rome_weekends.csv")
rome_weekends <-  rome_weekends %>%
  add_column(dayofweek = "weekend")

vienna_weekdays <- read.csv("vienna_weekdays.csv")
vienna_weekdays <- vienna_weekdays %>%
  add_column(dayofweek = "weekday")
vienna_weekends <- read.csv("vienna_weekends.csv")
vienna_weekends <-  vienna_weekends %>%
  add_column(dayofweek = "weekend")

# Combine datasets
amsterdam <- bind_rows(amsterdam_weekdays, amsterdam_weekends)
athens <- bind_rows(athens_weekdays, athens_weekends)
barcelona <- bind_rows(barcelona_weekdays, barcelona_weekends)
berlin <- bind_rows(berlin_weekdays, berlin_weekends)
budapest <- bind_rows(budapest_weekdays, budapest_weekends)
lisbon <- bind_rows(lisbon_weekdays, lisbon_weekends)
london <- bind_rows(london_weekdays, london_weekends)
paris <- bind_rows(paris_weekdays, paris_weekends)
rome <- bind_rows(rome_weekdays, rome_weekends)
vienna <- bind_rows(vienna_weekdays, vienna_weekends)

# Add city names to the dataframes
amsterdam <- amsterdam %>%
  add_column(city = "amsterdam")
athens <- athens %>%
  add_column(city = "athens")
barcelona <- barcelona %>%
  add_column(city = "barcelona")
berlin <- berlin %>%
  add_column(city = "berlin")
budapest <- budapest %>%
  add_column(city = "budapest")
lisbon <- lisbon %>%
  add_column(city = "lisbon")
london <- london %>%
  add_column(city = "london")
paris <- paris %>%
  add_column(city = "paris")
rome <- rome %>%
  add_column(city = "rome")
vienna <- vienna %>%
  add_column(city = "vienna")

fig_city <- bind_rows(amsterdam, athens, barcelona, berlin, budapest, lisbon, london, paris, rome, vienna)

fig_city <- unique(fig_city)

# Delete unnecessary columns from dataset
fig_city <- fig_city[,!names(fig_city) %in% 
      c("X", "rest_index", "rest_index_norm", "room_shared", "room_private", "metro_dist")]

# Reorder columns
col_order <- c("city", "dayofweek", "lat",
               "lng", "realSum", "room_type", "dist", "person_capacity", "bedrooms", "host_is_superhost", "multi", "biz", "cleanliness_rating", 
               "guest_satisfaction_overall", "attr_index", "attr_index_norm")

fig_city <- fig_city[, col_order]

# Remove shared rooms; too small amount of data for proper analysis
fig_city <- fig_city %>%
  filter(room_type != 'Shared room')

```

Final
```{r}
ui <- fluidPage(
  titlePanel("Question 2: Comparison between Vacation and Business Airbnb Rentals"),
   sidebarLayout(
    sidebarPanel( 
     selectInput("city", label = "City:",
              choices= unique(fig_city$city)),
      # Slider range for price
    sliderInput("realSum", label = "Price of Rental", min = 0, 
        max = 1000, value = c(0, 1000)),
      # Checkbox for day of the week
    checkboxGroupInput("dayofweek", label = "Weekday vs. Weekend Rental", 
    choices= unique(fig_city$dayofweek), selected = c("weekday", "weekend")),
      # Checkbox for room type
    checkboxGroupInput("room_type", label = "Rental Room Type", 
    choices= unique(fig_city$room_type), selected = c("Private room", "Entire home/apt")),
    # Radio button for trend lines
    radioButtons("trend_lines", label = "Trend Lines", 
    choices= c("No trend", "Overall trend", "All trends"), selected = "No trend")
  ),
    mainPanel(
      tabsetPanel(
      tabPanel("Trend Scatterplot", plotOutput("scatterplot")),
      tabPanel("Violin and Boxplot", plotOutput("violinplot")),
      tabPanel("Data", dataTableOutput("data_table")),
      tabPanel("Variable Summary", verbatimTextOutput("summary_var")))
  )))

server <- function(input, output){
    
    output$scatterplot <- renderPlot({
     
     fig_city <- fig_city %>% filter(between(realSum, min(input$realSum), max(input$realSum)))
     fig_city <- fig_city %>% filter(dayofweek %in% input$dayofweek)
     fig_city <- fig_city %>% filter(room_type %in% input$room_type)
     newbiz <- c("0" = "Vacation", "1" = "Business")
     
    graph1 <- ggplot(fig_city[fig_city$city==input$city,], aes(x=dist, y=realSum, color=room_type)) +
      geom_point(alpha=0.3) + facet_grid(biz~., labeller = labeller(biz = newbiz)) +
      xlab("Distance from City Center (km)") + ylab("Price of Airbnb (USD)") + 
      ggtitle("Graph 2: Relationship between Airbnb Price, Location, and Purpose of Rental") + 
      theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1)) +
      ylim(min(input$realSum), max(input$realSum)) +
      xlim(0, 10) +
      theme_bw() + scale_color_manual(values =  c("Private room"='coral',
        "Entire home/apt"='lightblue')) +
       labs(caption = "The figure above demonstrates a slight negative/inverse trend between Airbnb price and distance from the city center regardless of travel 
       purpose (vacation vs. business). The trend is robust against changes in the data manipulated using the widgets. Users can visualize the trend across 
       other secondary factors such as type of room rental, European city, price limits, and whether it is a 
       weekend or weekday rental. The trend lines also demonstrate a 95% confidence band around the trend lines.") +
       theme(plot.caption = element_text(face = "bold"))
    
    if(input$trend_lines == "No trend"){
      graph1
    } else if(input$trend_lines == 'Overall trend'){
      graph1 + geom_smooth(aes(group=NA), method=lm, color='black')
    } else if (input$trend_lines == 'All trends'){
      graph1 + geom_smooth(aes(linetype=room_type), method=lm, color='black') +
        scale_linetype_manual(values=c("longdash", "twodash"))
    }
    
  })
    
    output$violinplot <- renderPlot({
     
     fig_city <- fig_city %>% filter(between(realSum, min(input$realSum), max(input$realSum)))
     fig_city <- fig_city %>% filter(dayofweek %in% input$dayofweek)
     fig_city <- fig_city %>% filter(room_type %in% input$room_type)
     newbiz <- c("0" = "Vacation", "1" = "Business")
     
     ggplot(fig_city[fig_city$city==input$city,], aes(x=room_type, y=dist, color=room_type)) + 
      geom_boxplot(scale="width", lwd=1, outlier.shape=NA) + coord_flip() + xlab("Room Type") + ylab("Distance from City Center (km)") +
      geom_violin(scale="width", fill=alpha("grey",0.5), color=NA) + coord_flip() +
      facet_grid(biz~., labeller = labeller(biz = newbiz)) +
      ggtitle("Graph 2.1: The Relationship Between Location and Purpose of Rental") + 
      theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1)) +
      ylim(0, 10) +
      theme_bw() +
      scale_color_manual(values =  c("Private room"='coral',
        "Entire home/apt"='lightblue')) +
       guides(color = guide_legend(order = 1), size = guide_legend(order = 2)) +
       labs(caption = "As an extension of the first graph, the chart above demonstrates the relationship between Airbnb location 
            and purpose of rental when considering factors such as city, price, and time of week. While a relationship exists 
            between all Airbnb rentals and distance from the city center, this trend is more profound with business rather than vacation rentals.") +
       theme(plot.caption = element_text(face = "bold"))
  })
    
    output$data_table <- renderDataTable({
      fig_city <- fig_city %>% filter(between(realSum, min(input$realSum), max(input$realSum)))
      fig_city <- fig_city %>% filter(dayofweek %in% input$dayofweek)
      fig_city <- fig_city %>% filter(room_type %in% input$room_type)
      fig_city[fig_city$city==input$city, c("city", "dayofweek", "room_type", "realSum", "person_capacity", "bedrooms", "dist", "attr_index")]
    })
    
    output$summary_var <- renderPrint({
      fig_city <- fig_city %>% filter(between(realSum, min(input$realSum), max(input$realSum)))
      fig_city <- fig_city %>% filter(dayofweek %in% input$dayofweek)
      fig_city <- fig_city %>% filter(room_type %in% input$room_type)
      summary(fig_city[fig_city$city==input$city, c("realSum", "person_capacity", "bedrooms", "dist", "attr_index")])
    })
}

shinyApp(ui = ui, server = server) 
```


